# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: greet.proto for package 'greet'

require 'grpc'
require 'greet_pb'

module Greet
  module Greeter
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'greet.Greeter'

      rpc :SayHello, ::Greet::HelloRequest, ::Greet::HelloReply
      rpc :SayHelloAgain, ::Greet::HelloRequest, ::Greet::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
